steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'bq-timeline', '--trigger-topic', 'bq-timeline', '--runtime', 'python39', '--entry-point', 'bq-timeline']
  dir: 'code/bq-timeline'